### ISSUE TITLE
Newest UI update breaks the theme.

### ISSUE THREAD

**Issue by Oroborius** [DiscordStyles/FrostedGlass#116]
### Describe the bug

Several UI elements have grey covering elements. Also breaks further with HSL.

### To Reproduce

Use Discord UI Visual Refresh

### Screenshots

![Image](https://github.com/user-attachments/assets/f2ba01f4-7e13-4fd2-8cc4-83d0d869e09b)

### Infomation (please complete the following information)

**Discord channel**: Stable/
**OS**: _Windows
**Mod**: Vencord
**Discord language**: English

### Additional context

You probably know this is broken but please let me know if this gets fixed or is planning on being fixed anytime soon. Thanks~!

**Comment by Oroborius** [comment]
I've done a little bit of digging but these changes fix most of the issues for me, it's just a band-aid fix for the theme but should work for most:

```css
/**
 * @nameFrosted Glass Fixes
 * @author Oroborius
 * @version 1.0.0
 * @description Fixes breaking UI bugs in Discord when using Frosted Glass Theme.
 * @authorId 1087313527376711711
*/



/* Frosted Glass Theme Fixes */

#app-mount .chatContent_f75fb0 {
  background: linear-gradient(rgba(0, 0, 0, 0.0), transparent);
}

#app-mount .channelTextArea_f75fb0 { margin-bottom: var(--custom-chat-input-margin-bottom); background-color: rgba(0, 0, 0, 0.2) }

#app-mount .themedBackground__74017 { background: linear-gradient(rgba(0, 0, 0, 0.0), transparent); }

#app-mount .content__908e2 {
  border: unset;
  border-radius: unset;
  background: transparent !important;
}
```

Also this is more pertaining to me since I use no padding but this fixes the weird sizing/padding on left with Horizontal Server List:
```css
/**
 * @name Horizontal Server List Fixes
 * @author Oroborius
 * @version 1.0.0
 * @description Small fixes for Horizontal Server List when not using padding.
 * @authorId 1087313527376711711
*/

:root {
  /* Horizontal Server List Fixes */
  --size-sm: 0;
  --custom-guild-list-width: 65px;
  --custom-app-top-bar-height: 25px;
}
```
