### ISSUE TITLE
emoji list missing in message edit

### ISSUE THREAD

**Issue by thc282** [DiscordStyles/FrostedGlass#121]
### Describe the bug
The emoji list is missing in the message editing

### To Reproduce
Edit any message, open the emoji

### Screenshots
![Image](https://github.com/user-attachments/assets/cd7fd54f-9673-4c97-b792-9f98422fe087)

### Infomation (please complete the following information)

**Discord channel**: _Stable
**OS**: _Windows
**Mod**: _Vencord
**Discord language**: _ZH_TW

**Comment by thc282** [comment]
year past, no any update
and i cant find out the bug either 😄

**Comment by thc282** [comment]
update:
i just find out the root cause

# QuickCSS Fix:
```css
/* 
* Frosted Glass Theme Edit Emoji Panel fix
* ref: https://github.com/DiscordStyles/FrostedGlass/issues/121
*/
#app-mount .appAsidePanelWrapper_a3002d .layerContainer__59d0d .clickTrapContainer__59d0d #emoji-picker-tab-panel{
  overflow: visible; 
}
.emojiPickerHasTabWrapper_c0e32c .emojiPicker_c0e32c{
  height: var(--custom-emoji-picker-constants-emoji-picker-height);
}
```

## 1. remove this `height: 100%` make it work, it will follows the `--custom-emoji-picker-constants-emoji-picker-height`
<img width="1618" height="832" alt="Image" src="https://github.com/user-attachments/assets/b5975605-3a7d-4de7-b385-9797f0c2aba2" />

## 2. exclude `#app-mount .appAsidePanelWrapper_a3002d .layerContainer__59d0d .clickTrapContainer__59d0d #emoji-picker-tab-panel` to use overflow
<img width="660" height="261" alt="Image" src="https://github.com/user-attachments/assets/a48c479e-7347-4c1f-ad06-28dbe01e3b1e" />

## 3. now should be fixed
<img width="570" height="959" alt="Image" src="https://github.com/user-attachments/assets/706d963f-ddc8-4da4-acf5-4ddc28bc01dc" />
