### ISSUE TITLE
When you change from the default color, the text-bar gets a bug

### ISSUE THREAD

**Issue by Simone-rar** [DiscordStyles/FrostedGlass#17]
Uh, so I changed the default colors to red and blue gradient.
But now when ever I wanna mention a user, and when his ping is in the text box  ( like @gudguy Hey dude Wassup)  it gets bugged, I tried reinstalling but the thing remained the same.
See the attached video if you didn't understand what I said

https://user-images.githubusercontent.com/74021010/132081072-6f8d8af3-3f27-4450-9972-b9a9c5e8758a.mp4

**Comment by dottiekh** [comment]
This is SUPER late but I've finally figured it out as this was driving me insane:

Put this in your Custom CSS:
```css
.textArea-2CLwUE.textAreaSlate-9-y-k2.slateContainer-3x9zil.spellCheckOverlay-cNSap5 {
    display: none !important;
}
```

For some reason an element appears once you keyup in the text area for sending messages and it obscures the text with the gradient. Hiding this element allows text to appear on top of the gradient again.

![image](https://user-images.githubusercontent.com/34873184/189480609-d93a6f28-51b4-49b7-a0f8-01d104ce8a1c.png)
