### ISSUE TITLE
thread window in side-by-side view is not darkened

### ISSUE THREAD

**Issue by RisenFalcon** [DiscordStyles/FrostedGlass#38]
### Describe the bug
When opening a thread in side-by-side view, the background image is not darkened.

### To Reproduce  
Open a thread in side-by-side view

### Screenshots
![image](https://user-images.githubusercontent.com/97866817/168739368-8d2df890-1a0e-4695-a720-4258184e1244.png)

### Infomation (please complete the following information)
**Discord channel**: *PTB*  
**OS**: *Windows 10*  
**Mod**: *BetterDiscord*  
**Discord language**: *English*  

### Additional context
I solved it in my own custom css with:
```css
.container-3XgAHv {
  content: "";
  background-position: var(--background-image-position, center);
  background-size: var(--background-image-size, cover);
  background-color: rgba(0, 0, 0, var(--middle-brightness));
}
```
